### PR TITLE
add written off status for accounting

### PR DESCRIPTION
**Pull request by codegeschrei**
fix for issue https://github.com/resmio/resmio/issues/2996

### CODE REVIEW

**Comment by mmarder** [comment]
looks good to me but test failed.

**Review by JannKleen — APPROVED** [review]
Looks good except for the pep8 error

**Comment by mmarder** [comment]
@Atisheh @JannKleen what is the status here? is that deployed? can we use it?

**Comment by codegeschrei** [comment]
@mmarder as far as I know, it's not deployed yet

**Pull request merged**
